package org.tuboleta.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-14T23:13:24.868-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.tuboleta.org/demo/", name = "TuBoletaSystemServices")
@XmlSeeAlso({ObjectFactory.class})
public interface TuBoletaSystemServices {

    @WebMethod
    @RequestWrapper(localName = "realizarReserva", targetNamespace = "http://www.tuboleta.org/demo/", className = "org.tuboleta.demo.RealizarReserva")
    @ResponseWrapper(localName = "realizarReservaResponse", targetNamespace = "http://www.tuboleta.org/demo/", className = "org.tuboleta.demo.RealizarReservaResponse")
    public void realizarReserva(
        @WebParam(name = "reservas", targetNamespace = "")
        java.util.List<org.tuboleta.demo.RealizarReserva.Reservas> reservas,
        @WebParam(mode = WebParam.Mode.OUT, name = "respuesta", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> respuesta,
        @WebParam(mode = WebParam.Mode.OUT, name = "estado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> estado,
        @WebParam(mode = WebParam.Mode.OUT, name = "fechaReserva", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaReserva
    );

    @WebMethod
    @RequestWrapper(localName = "obtenerReserva", targetNamespace = "http://www.tuboleta.org/demo/", className = "org.tuboleta.demo.ObtenerReserva")
    @ResponseWrapper(localName = "obtenerReservaResponse", targetNamespace = "http://www.tuboleta.org/demo/", className = "org.tuboleta.demo.ObtenerReservaResponse")
    public void obtenerReserva(
        @WebParam(mode = WebParam.Mode.INOUT, name = "idReserva", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> idReserva,
        @WebParam(mode = WebParam.Mode.OUT, name = "estado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> estado,
        @WebParam(mode = WebParam.Mode.OUT, name = "fechaReserva", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaReserva,
        @WebParam(mode = WebParam.Mode.OUT, name = "boletas", targetNamespace = "")
        javax.xml.ws.Holder<org.tuboleta.demo.ObtenerReservaResponse.Boletas> boletas
    );

    @WebMethod
    @RequestWrapper(localName = "cancelarReserva", targetNamespace = "http://www.tuboleta.org/demo/", className = "org.tuboleta.demo.CancelarReserva")
    @ResponseWrapper(localName = "cancelarReservaResponse", targetNamespace = "http://www.tuboleta.org/demo/", className = "org.tuboleta.demo.CancelarReservaResponse")
    public void cancelarReserva(
        @WebParam(name = "idReserva", targetNamespace = "")
        java.lang.String idReserva,
        @WebParam(mode = WebParam.Mode.OUT, name = "respuesta", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> respuesta,
        @WebParam(mode = WebParam.Mode.OUT, name = "estado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> estado,
        @WebParam(mode = WebParam.Mode.OUT, name = "fechaReserva", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaReserva
    );
}
